#!/bin/bash

# 2011/01/26:
# - OSCam start/stop/restart example script - http://www.streamboard.tv/wiki/OSCam/en/ShellCommands#Starting_and_stopping_OSCam

# 2018/07/16:
# - s3n0 edit (OpenATV target file:  /etc/init.d/softcam)
# - this softcam script file can also be downloaded directly from my github profile:
#      wget -O /etc/init.d/softcam --no-check-certificate https://github.com/s3n0/e2scripts/raw/master/softcam && chmod +x /etc/init.d/softcam
# - in many Enigmas, the /etc/init.d/softcam startup script is directly supported through the embedded source code
#   (for example, the OpenATV source code: /lib/python/Plugins/Extensions/Infopanel/plugin.py)
# - so just copy the bash-script into the /etc/init.d folder and nothing else is needed (symbolic links to /etc/rc3.d and /etc/rc4.d are not necessary)
# - please do not forget to set the execution rights for bash script:  chmod +x /etc/init.d/softcam
# - if the '/etc/init.d/softcam' script auto start feature is not implemented in your Enigma2, then you must additionally create a symbolic link:
#      ln -sf /etc/init.d/softcam /etc/rc3.d/S90softcam
#   ...for remove (uninstall) the symbolic link you can simple delete the link:
#      rm -f /etc/rc3.d/S90softcam
#   ...you can also use the automated tool for adding the startup sym-links to all default run-levels:
#      update-rc.d softcam defaults 90
#   ...for remove (uninstall) startup sym-links from all run-levels use the following command:
#      update-rc.d -f softcam remove

# 2019/06/15
# - s3n0 edit
# - remake the logging concept (logging output via function)
# - some cosmetic improvements

# 2019/06/23
# - s3n0 edit
# - some changes in start/stop/restart functions






# ####################  USER SETUP  ########################
# ----------------------------------------------------------
# SOFTCAM BINARY DIRECTORY:
softcam_dir='/usr/bin'
# ----------------------------------------------------------
# SOFTCAM PROCESS NAME (BINARY FILE NAME):
softcam_exec='oscam'
# ----------------------------------------------------------
# SOFTCAM ARGUMENTS:    (a note: argument "-c" for OSCam determines a configuration directory, for more info use "/usr/bin/oscam --help")
softcam_args='-b -r 2 -c /etc/tuxbox/config/oscam'
# ----------------------------------------------------------
# Waiting time to kill the softcam process by standard SIGTERM (-15). Then softcam process will be killed with force SIGKILL (-9).
softcam_kill_waiting=3
# ----------------------------------------------------------
# LOG FILE FOR THE SOFTCAM HANDLING:
softcam_logfile='/tmp/oscam_handling.log'
softcam_logfile_sizemax=45000       # max. file size [Bytes]
# ----------------------------------------------------------
# PRIVATE VARIABLES:
hrline='------------------------------------------------------------'
helptext="USAGE:     bash /etc/init.d/softcam <ARGUMENT>
ARGUMENT:  start......the process will be started only if it's not running
           restart....the process will be stopped only if it's running & then will be started
           stop.......stop and unload the $softcam_exec service from memory"
# ----------------------------------------------------------
# ###############  END OF THE USER SETUP  ##################







# FUNCTIONS ************************************************

fLog() {
    if [[ $1 != *"-----"* ]]; then
        logline=`date '+%Y-%m-%d %H:%M:%S'`" $1"          # only if it is not a separating line (minus characters), then I insert a timestamp at the beginning
    else
        logline="$1"
    fi
    
    #echo "$logline" > /dev/null                          ### null device   <---  log will disabled (do nothing)
    #echo "$logline" >> $softcam_logfile                  ### file
    #echo "$logline" >> $softcam_logfile 2>&1             ### file + stderr
    #echo "$logline" | tee -a $softcam_logfile            ### file + stdout(display)
    echo "$logline" 2>&1 | tee -a $softcam_logfile       ### file + stdout(display) + stderr
    
    #### reduction the log filesize, if neccessary (delete first 20 lines):
    if [ -f "$softcam_logfile" ] && [ $(stat -c%s "$softcam_logfile") -gt $softcam_logfile_sizemax ]; then sed -i -e 1,20d "$softcam_logfile"; fi
}

fStop() {
    if ! pidof $1 > /dev/null; then
        fLog "No $1 process is running."
    else
        fLog "Stopping $1..."
        fLog "...sending a default SIGTERM signal to PID $(pidof $1)"
        kill -15 $(pidof $1) > /dev/null
        sleep 0.8s       # changed from 1s to 0.8s, as the '/lib/python/Screens/SoftcamSetup.py' restarts the softcam script too quickly with the 'stop' argument and 1s later it immediately starts the script again with the argument 'start' i.e. without using the 'restart' argument ! unfortunately my softcam script is testing as the first normal softcam stopping, which can take about 0.3s-0.6s
        if pidof $1 > /dev/null; then
            i=1
            while expr $i != $softcam_kill_waiting > /dev/null
            do
                if pidof $1 > /dev/null; then
                    fLog "...waiting for termination: $i of max. $softcam_kill_waiting seconds"
                    sleep 1
                else
                    fLog "...$1 was successfully terminated using the default SIGTERM signal."
                    break
                fi
                i=`expr $i + 1`
            done
        else
            fLog "...$1 was successfully terminated using the default SIGTERM signal."
        fi
        if pidof $1 > /dev/null; then
            fLog "...sending a forced SIGKILL signal to $1 process"
            killall -9 $1 > /dev/null
            if pidof $1 > /dev/null; then
                fLog "...$1 was not killed by a forced SIGKILL signal! Probably a system error?!"
            else
                fLog "...$1 was killed using the forced SIGKILL signal."
            fi
        fi
    fi
}

fStart() {
    fLog "Starting $1..."
    if pidof $1 > /dev/null; then
        fLog "...$1 process has already started and is still running."
    else
        $softcam_dir/$1 $softcam_args > /dev/null
        fLog "command-line executed:   $softcam_dir/$1 $softcam_args"
        sleep 0.8s
        if pidof $1 > /dev/null; then
            fLog "...$1 was successfully started."
        else
            fLog "ERROR! $1 start failed!"
        fi
    fi
}

fRestart() {
    if pidof $1 > /dev/null; then fStop $1; fi       # start the process - the process will be stopped/killed only if it's running
    fStart $1
}







# CHECKING THE EXISTENCE OF THE BINARY/EXEC FILE

if [ ! -f "$softcam_dir/$softcam_exec" ]; then
    fLog "ERROR! Executable binary file '$softcam_dir/$softcam_exec' does not exist!"
    fLog "$hrline"
    exit 1
fi



# CALL FUNCTIONS ACCORDING TO INPUT ARGUMENTS OF BASH SCRIPT **************************

case "$1" in
    start)
        fStart "$softcam_exec"
        fLog "$hrline"
        ;;
    stop)
        fStop "$softcam_exec"
        fLog "$hrline"
        ;;
    restart|reload|force-reload)
        fRestart "$softcam_exec"
        fLog "$hrline"
        ;;
    *)
        fLog "UNKNOWN OR MISSING PARAMETER !"
        echo "$helptext" >$(tty)
        fLog "$hrline"
        exit 1
        ;;
esac



exit 0
